name: Build & Push docker

on:
  workflow_call:
    inputs:
      image_name:
        description: Image name without registry name & without tag
        required: true
        type: string
      tag:
        required: false
        default: "latest"
        type: string
      registry_name:
        required: true
        type: string
      dockerfile:
        required: false
        default: "./Dockerfile"
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:

    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2

    - name: Registry Log In
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry_name }}
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}

    - name: Build and push container image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ inputs.registry_name }}/${{ inputs.image_name }}:${{ github.sha }}
          ${{ inputs.registry_name }}/${{ inputs.image_name }}:${{ inputs.tag }}
        file: ${{ inputs.dockerfile }}

