name: Update deployments

on:
  workflow_call:
    inputs:
      image_name:
        description: Image name with registry name & without tag
        required: true
        type: string
      tag:
        required: true
        type: string
      overlay:
        required: true
        type: string
      workspace:
        required: true
        type: string
      application:
        required: true
        type: string
      kubernetes_deployments:
        description: comma separated deployments list owned to the service
        required: true
        type: string
      ssh_jumpbox_host:
        required: true
        type: string
      ssh_jumpbox_port:
        required: true
        type: string
      ssh_jumpbox_user:
        required: true
        type: string
      deployments-repository:
        required: false
        default: "granular-energy/granular-deployments"
        type: string
      kustomize-version:
        required: false
        default: "4.5.5"
        type: string
      wait-argocd-pull:
        required: false
        default: 5
        type: number
    secrets:
      private_access_token:
        required: true
      ssh_jumpbox_key:
        required: true

jobs:
  update-image:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout deployments repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.deployments-repository }}
        ref: main
        token: ${{ secrets.private_access_token }}

    - name: Install Kustomize
      run: |
        curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ inputs.kustomize-version }}/kustomize_v${{ inputs.kustomize-version }}_linux_amd64.tar.gz
        tar -xvzf kustomize.tar.gz
        rm kustomize.tar.gz
        chmod u+x ./kustomize

    - name: Setup git config
      run: |
        git config user.name "GranuBot"
        git config user.email "<>"

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/jumpbox.key
        chmod 600 ~/.ssh/jumpbox.key
        cat >>~/.ssh/config <<END
        Host jumpbox
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/jumpbox.key
          StrictHostKeyChecking no
          Port $SSH_PORT
        END
      env:
        SSH_USER: ${{ inputs.ssh_jumpbox_user }}
        SSH_KEY: ${{ secrets.ssh_jumpbox_key }}
        SSH_HOST: ${{ inputs.ssh_jumpbox_host }}
        SSH_PORT: ${{ inputs.ssh_jumpbox_port }}

    - name: Kustomize build and commit
      run: |
        cd ${{ inputs.workspace }}/overlays/${{ inputs.overlay }}
        $GITHUB_WORKSPACE/kustomize edit set image "${{ inputs.image_name }}=${{ inputs.image_name }}:${{ inputs.tag }}"
        if [ ! -z `git status --short`]; then
          git add -A
          git commit -m "Set `${{ inputs.image_name }}` image tag to `${{ inputs.tag }}` for ${{ inputs.workspace }}/overlays/${{ inputs.overlay }}"
          git push origin main
        fi

    - name: Sync Argocd
      run: |
        sleep ${{ inputs.wait-argocd-pull }}
        echo "argoc app sync"
        ssh jumpbox 'argocd app sync ${{ inputs.application }} --timeout 30'
        echo "argoc app wait --sync"
        ssh jumpbox 'argocd app wait --sync ${{ inputs.application }} --timeout 30'

    - name: Kubectl rollout restart deployment
      run: |
        echo "kubectl rollout restart deployment"
        ssh jumpbox 'echo "${{ inputs.kubernetes_deployments }}" | jq -c \'split(",")|.[]\' | while read deployment; do; kubectl -n $(argocd app get ${{ inputs.application }} -ojson | jq -r ".spec.destination.namespace") rollout restart deployment \$deployment; done;'
